name = "PyProteinMPNN"
uuid = "ba507b30-8e11-4219-9ced-db99387ea03d"
authors = ["aronStalmarck <aron.stalmarck@gmail.com> and contributors"]
version = "1.0.3-DEV"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Pkg = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
